In [1]:
import pandas as pd
import numpy as np
import sklearn as sns

In [2]:
df = pd.read_csv("insurance_data.csv")

In [3]:
df

      age  gender     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   gender    1338 non-null   str
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 73.3 KB

In [5]:
df.isnull()

        age  gender    bmi  children  smoker  region  charges
0     False   False  False     False   False   False    False
1     False   False  False     False   False   False    False
2     False   False  False     False   False   False    False
3     False   False  False     False   False   False    False
4     False   False  False     False   False   False    False
...     ...     ...    ...       ...     ...     ...      ...
1333  False   False  False     False   False   False    False
1334  False   False  False     False   False   False    False
1335  False   False  False     False   False   False    False
1336  False   False  False     False   False   False    False
1337  False   False  False     False   False   False    False

[1338 rows x 7 columns]

In [6]:
df.isnull().sum()

age         0
gender      0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [7]:
df.value_counts()

age  gender  bmi     children  smoker  region     charges
19   male    30.590  0         no      northwest  1639.56310     2
     female  27.900  0         yes     southwest  16884.92400    1
18   male    33.770  1         no      southeast  1725.55230     1
28   male    33.000  3         no      southeast  4449.46200     1
33   male    22.705  0         no      northwest  21984.47061    1
                                                                ..
50   male    30.970  3         no      northwest  10600.54830    1
18   female  31.920  0         no      northeast  2205.98080     1
             36.850  0         no      southeast  1629.83350     1
21   female  25.800  0         no      southwest  2007.94500     1
61   female  29.070  0         yes     northwest  29141.36030    1
Name: count, Length: 1337, dtype: int64

In [8]:
df.duplicated().sum()

np.int64(1)

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df['gender'].unique()

<StringArray>
['female', 'male']
Length: 2, dtype: str

In [11]:
gender ={
    'female':0, 'male':1
}

In [12]:
df['gender']=df['gender'].map(gender)

In [13]:
df

      age  gender     bmi  children smoker     region      charges
0      19       0  27.900         0    yes  southwest  16884.92400
1      18       1  33.770         1     no  southeast   1725.55230
2      28       1  33.000         3     no  southeast   4449.46200
3      33       1  22.705         0     no  northwest  21984.47061
4      32       1  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50       1  30.970         3     no  northwest  10600.54830
1334   18       0  31.920         0     no  northeast   2205.98080
1335   18       0  36.850         0     no  southeast   1629.83350
1336   21       0  25.800         0     no  southwest   2007.94500
1337   61       0  29.070         0    yes  northwest  29141.36030

[1337 rows x 7 columns]

In [14]:
df['smoker'].unique()

<StringArray>
['yes', 'no']
Length: 2, dtype: str

In [15]:
smoker ={
    'yes':1, 'no':0
}

In [16]:
df['smoker']=df['smoker'].map(smoker)

In [17]:
df

      age  gender     bmi  children  smoker     region      charges
0      19       0  27.900         0       1  southwest  16884.92400
1      18       1  33.770         1       0  southeast   1725.55230
2      28       1  33.000         3       0  southeast   4449.46200
3      33       1  22.705         0       0  northwest  21984.47061
4      32       1  28.880         0       0  northwest   3866.85520
...   ...     ...     ...       ...     ...        ...          ...
1333   50       1  30.970         3       0  northwest  10600.54830
1334   18       0  31.920         0       0  northeast   2205.98080
1335   18       0  36.850         0       0  southeast   1629.83350
1336   21       0  25.800         0       0  southwest   2007.94500
1337   61       0  29.070         0       1  northwest  29141.36030

[1337 rows x 7 columns]

In [18]:
df['region'].unique()

<StringArray>
['southwest', 'southeast', 'northwest', 'northeast']
Length: 4, dtype: str

In [19]:
#region ={
    #'southwest':1, 'southeast':2, 'northwest':3, 'northeast':4
#}

In [20]:
#df['region']=df['region'].map(region)

In [21]:
df

      age  gender     bmi  children  smoker     region      charges
0      19       0  27.900         0       1  southwest  16884.92400
1      18       1  33.770         1       0  southeast   1725.55230
2      28       1  33.000         3       0  southeast   4449.46200
3      33       1  22.705         0       0  northwest  21984.47061
4      32       1  28.880         0       0  northwest   3866.85520
...   ...     ...     ...       ...     ...        ...          ...
1333   50       1  30.970         3       0  northwest  10600.54830
1334   18       0  31.920         0       0  northeast   2205.98080
1335   18       0  36.850         0       0  southeast   1629.83350
1336   21       0  25.800         0       0  southwest   2007.94500
1337   61       0  29.070         0       1  northwest  29141.36030

[1337 rows x 7 columns]

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
x=df.drop(columns=['charges','region'])
y=df['charges']

In [24]:
x

      age  gender     bmi  children  smoker
0      19       0  27.900         0       1
1      18       1  33.770         1       0
2      28       1  33.000         3       0
3      33       1  22.705         0       0
4      32       1  28.880         0       0
...   ...     ...     ...       ...     ...
1333   50       1  30.970         3       0
1334   18       0  31.920         0       0
1335   18       0  36.850         0       0
1336   21       0  25.800         0       0
1337   61       0  29.070         0       1

[1337 rows x 5 columns]

In [25]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1337, dtype: float64

In [26]:
x.duplicated().sum()

np.int64(2)

In [27]:
#x.drop_duplicates(inplace=True)

In [28]:
y.duplicated().sum()

np.int64(0)

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [30]:
x_train

      age  gender     bmi  children  smoker
1114   23       1  24.510         0       0
968    21       1  25.745         2       0
599    52       0  37.525         2       0
170    63       1  41.470         0       0
275    47       0  26.600         2       0
...   ...     ...     ...       ...     ...
1096   51       0  34.960         2       1
1131   27       1  45.900         2       0
1295   20       1  22.000         1       0
861    38       0  28.000         3       0
1127   35       0  35.860         2       0

[1069 rows x 5 columns]

In [31]:
x_test

      age  gender     bmi  children  smoker
900    49       1  22.515         0       0
1064   29       0  25.600         4       0
1256   51       0  36.385         3       0
298    31       1  34.390         3       1
237    31       1  38.390         2       0
...   ...     ...     ...       ...     ...
534    64       1  40.480         0       0
542    63       0  36.300         0       0
760    22       0  34.580         2       0
1284   61       1  36.300         1       1
1285   47       0  24.320         0       0

[268 rows x 5 columns]

In [32]:
y_train

1114     2396.09590
968      3279.86855
599     33471.97189
170     13405.39030
275      9715.84100
           ...
1096    44641.19740
1131     3693.42800
1295     1964.78000
861      7151.09200
1127     5836.52040
Name: charges, Length: 1069, dtype: float64

In [33]:
y_test

900      8688.85885
1064     5708.86700
1256    11436.73815
298     38746.35510
237      4463.20510
           ...
534     13831.11520
542     13887.20400
760      3925.75820
1284    47403.88000
1285     8534.67180
Name: charges, Length: 268, dtype: float64

In [34]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(1069, 5) (268, 5) (1069,) (268,)

In [35]:
x_train, x_test, y_train, y_test = x_train, x_test, y_train, y_test.drop_duplicates()

In [36]:
x

      age  gender     bmi  children  smoker
0      19       0  27.900         0       1
1      18       1  33.770         1       0
2      28       1  33.000         3       0
3      33       1  22.705         0       0
4      32       1  28.880         0       0
...   ...     ...     ...       ...     ...
1333   50       1  30.970         3       0
1334   18       0  31.920         0       0
1335   18       0  36.850         0       0
1336   21       0  25.800         0       0
1337   61       0  29.070         0       1

[1337 rows x 5 columns]

In [37]:
df

      age  gender     bmi  children  smoker     region      charges
0      19       0  27.900         0       1  southwest  16884.92400
1      18       1  33.770         1       0  southeast   1725.55230
2      28       1  33.000         3       0  southeast   4449.46200
3      33       1  22.705         0       0  northwest  21984.47061
4      32       1  28.880         0       0  northwest   3866.85520
...   ...     ...     ...       ...     ...        ...          ...
1333   50       1  30.970         3       0  northwest  10600.54830
1334   18       0  31.920         0       0  northeast   2205.98080
1335   18       0  36.850         0       0  southeast   1629.83350
1336   21       0  25.800         0       0  southwest   2007.94500
1337   61       0  29.070         0       1  northwest  29141.36030

[1337 rows x 7 columns]

In [38]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [39]:
lr.fit(x_train,y_train)

LinearRegression()

In [40]:
southwest = lr.predict(x_test)

In [41]:
southwest

array([ 7780.09204548,  5977.83338997, 14215.82300956, 31590.59473466,
        9223.64922442, 13438.43822409, 29841.65667782,  1685.03795715,
       10919.46514725, 11281.04050309, 10418.78669104, 33059.36084168,
       30531.50988264, 17420.0023959 , 10214.90616935,  9749.75223135,
        4298.47335596, 32007.67725019,  3488.96062241,  5583.27330599,
        3845.53703027, 29815.02239719, 15103.39914515, 30646.34708594,
       30908.30211535,  5363.08477297, 35705.172843  , 36714.56751572,
       10928.83748576, 13689.22034633,  5994.25520485, 13015.10761713,
         842.10884744, 12332.40611586, 39769.78804625, 12472.16793437,
        4941.6340669 ,  3962.34504306, 31334.30270026,  9347.27340131,
        6423.31161511, 29743.01929574, 35062.57980736, 11806.50755259,
        7409.90515685,  3638.00400509,  5572.08908023,  9165.34126485,
        4217.22289854,  9367.5521687 ,  6914.22550367, 11443.85328341,
       30801.79761652,  3861.35683277, 11172.20169464, 10108.79403925,
       10412.98753451,  2424.7972324 , 31428.46966997,  9330.94873716,
       15809.55411917,  8489.70041893, 12504.40317537,  1161.34364986,
       17005.95308461, 10314.83836126, 10019.85307693, 30951.96634184,
       24943.12147173, 16025.10200435,  7335.01138907,  2465.70070659,
        6760.76867753,  -313.48366029, 11248.81670957,  -804.14771802,
       17151.61745787,  8915.06491216,  8031.78271134, 12378.16612902,
        5390.67936613, 18708.35263296, 14932.95282883, 11271.55462952,
       36000.56194354, 13542.68177188,  3947.26459085,  2690.96764336,
        6043.31580845,  4373.33318405, 15371.82440461, 28145.94818216,
        5784.39905438,  3428.97186602,  2343.49618246, 35369.70441928,
       14569.05448195,  9246.4265579 ,  4494.0097257 ,  8324.14458127,
       14189.9155896 , 15289.17705514, 32562.37416826, 14694.68965016,
       32584.90764455,    74.98218339, 30592.15735183, 26981.97238279,
       13803.29050177,  6231.88229719,  8483.77017197, 11529.52772924,
        7947.23256602,  9703.07742708,  6245.07764316,  5630.89683571,
        1917.30260673,  3363.16639772,  7230.6604141 ,  9503.37744469,
       36287.55005748,  7684.81194889, 11823.07684222,  9514.21572568,
        8974.41160324,  9822.95909442,  4914.87480373, 12591.57777186,
       29993.2739245 , 39044.30303566, 35908.8148471 , 11687.99494548,
        2787.35552188, 11440.97275927, 10500.68427953,  4994.96584456,
       34693.48952168, 29512.21448075, 25388.75237697,  5144.45843061,
        6932.69758915,  5302.13584364, 36659.9688943 , 10463.51317804,
        5749.87502517,  8517.2268642 , 10427.6540283 ,  8681.00489391,
       35269.75467201, 13950.52824467,  9955.25137026,  6462.90286907,
        7270.91038085, 16853.22311915,  7364.40121665, 26681.42555164,
       36669.15941562, 16003.27860167, 10248.73767496, 10990.41730142,
       12216.98354765,  3813.99458136, 12702.98419684, 13445.6177541 ,
       35551.13065195, 32823.8924839 , 13197.19867583, 25552.39411091,
        2177.15053624,  1722.55604555,  4879.48151019,  5229.82100561,
        4787.1149749 , 10184.90315039,  9943.19788017, 26306.21189393,
        2615.65874613, 10921.04996438,  6919.88329869, 11670.64196052,
       14835.42309443,  4947.34869121, 11328.51018168, 10061.1024959 ,
       32885.97702697, 10842.37337097,  7374.63137202,  6030.00679317,
         392.26256066, 31636.32067388,  7635.10394038, 32695.27456972,
       12142.07833239,  6330.55895856,  1304.43402486,  2388.31357806,
       32262.98661945,  5233.44478011, 13594.20673339, 16940.47704252,
       26232.73868144, 26119.40059203,  6889.82330548, 12478.84260272,
       28662.77586706,  8084.75098885, 10170.7991212 , 10443.38812755,
        3101.51178631, 34556.6472381 , 31776.76397125,  9633.77317218,
        6176.26680243,  7611.36032608, 11220.94341698,  4960.89608984,
        4925.85471472, 11731.2843586 ,  9219.48561178,  2523.76404068,
        3744.86055657, 37759.57109926, 37279.06294113, 13535.21222922,
       11112.8035085 , 38040.99260063, 33925.65875766,  6998.82117041,
       26477.18180365,  4078.78461885, 16004.13669237, 29626.8988697 ,
        5681.61547542,  9576.76091961,  8495.46043577,  9567.25749068,
        9327.77312926,  4523.89310172,  5544.82391326,  4936.83449683,
        6422.66421555,  4663.75207631,  5513.52608983,  9056.97949159,
        1120.12219695,  8432.11412004,  4046.21370952, 11059.17637859,
        2175.38403616, 10221.94420359,  3775.3292975 , 11466.81229984,
       12471.37306006, 14028.00614756, 36850.62596972, 22819.1917562 ,
        9770.78582546,  7433.95530239,  9124.21058629, 12037.31236758,
       29227.95901345, 38161.66914229, 15081.48497347, 17006.56134448,
       15565.09981797,  5902.49666093, 38571.21383302,  7918.53032517])

In [42]:
x

      age  gender     bmi  children  smoker
0      19       0  27.900         0       1
1      18       1  33.770         1       0
2      28       1  33.000         3       0
3      33       1  22.705         0       0
4      32       1  28.880         0       0
...   ...     ...     ...       ...     ...
1333   50       1  30.970         3       0
1334   18       0  31.920         0       0
1335   18       0  36.850         0       0
1336   21       0  25.800         0       0
1337   61       0  29.070         0       1

[1337 rows x 5 columns]

In [43]:
lr.predict([[19,	0,	27.900,	0,	1]])

c:\Users\om sai compurer1\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([25089.26781169])

In [44]:
lr.predict(x_train)

array([ 1913.28139775,  2868.42936746, 14275.33486501, ...,
         936.91190884,  8415.15856955,  9531.89800259], shape=(1069,))

In [45]:
from sklearn.svm import SVR
sv = SVR()

In [46]:
import imblearn
from imblearn.over_sampling import SMOTE

In [47]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

#Apply SMOTE to the training data
sm = SMOTE(random_state=42)

In [48]:
sv.fit(x_train, y_train)

SVR()

In [49]:
pred =sv.predict(x_test)
pred

array([9284.70136804, 9153.31174498, 9304.75398383, 9167.10855523,
       9170.26299602, 9291.53080107, 9132.26460727, 9124.54795089,
       9248.42951737, 9288.82724377, 9349.35852994, 9308.43755094,
       9172.19186389, 9352.43387792, 9194.13768871, 9260.16986502,
       9119.77267228, 9198.76431594, 9139.31242356, 9153.05227249,
       9119.8098343 , 9195.34642876, 9291.02999672, 9216.35093044,
       9179.63934438, 9122.93761832, 9243.45474927, 9355.12475809,
       9289.90490894, 9284.23662686, 9164.63279667, 9298.26552957,
       9115.82073123, 9348.06474049, 9317.22470713, 9304.63664288,
       9117.23833368, 9160.35789186, 9308.88135491, 9267.14093131,
       9132.9016745 , 9242.03045669, 9248.81244363, 9304.15858571,
       9262.44810549, 9147.71083781, 9124.1846916 , 9245.9736461 ,
       9147.66752127, 9217.86509542, 9149.64723119, 9223.96520916,
       9244.15983574, 9120.04766368, 9241.24850652, 9253.72020418,
       9302.00287731, 9135.82112805, 9179.80161485, 9231.5794647 ,
       9291.09814042, 9191.21061966, 9310.53161326, 9114.35536245,
       9308.37135413, 9311.70991267, 9213.40717327, 9245.24484835,
       9116.19284773, 9362.56742766, 9299.78132962, 9114.21621806,
       9229.02505143, 9129.38224387, 9327.78767902, 9122.61072438,
       9353.18506781, 9179.61306975, 9283.75116863, 9353.36572222,
       9143.48642909, 9306.49504295, 9354.43815686, 9248.31458949,
       9364.75281965, 9349.43493907, 9158.03097048, 9114.0216583 ,
       9128.59965957, 9128.30855269, 9354.87509801, 9158.8972786 ,
       9149.07573997, 9121.35814792, 9115.93039769, 9317.60883484,
       9316.12418456, 9266.9727861 , 9125.90847204, 9257.80912344,
       9366.70266556, 9334.92657223, 9311.04232098, 9317.43141959,
       9191.57986266, 9118.99221148, 9183.62872997, 9122.11901211,
       9329.45634266, 9188.20323806, 9203.01772574, 9342.864709  ,
       9184.10854139, 9180.18973394, 9132.45036657, 9134.60833362,
       9116.32892064, 9115.82581311, 9139.39736348, 9292.26774071,
       9329.66600514, 9179.16848492, 9256.54023306, 9191.46656586,
       9259.64949032, 9232.29940682, 9136.24529533, 9357.38479161,
       9140.27141564, 9365.65909001, 9358.05911686, 9263.70458645,
       9134.44991674, 9295.4010739 , 9182.54216406, 9115.41584219,
       9256.99251262, 9249.01312429, 9116.19379738, 9132.89942502,
       9170.07440789, 9138.68809906, 9252.11329708, 9319.36339864,
       9125.64265528, 9218.04058287, 9186.17628845, 9252.25574128,
       9277.74330625, 9363.12610425, 9212.07042908, 9201.20918302,
       9189.25094381, 9367.21665731, 9222.23595119, 9117.87580584,
       9215.54169731, 9270.92893679, 9282.95808498, 9297.32529061,
       9323.34303191, 9194.78473942, 9340.20012225, 9345.65593079,
       9340.11835256, 9254.20466908, 9304.33933235, 9118.50129725,
       9135.30500598, 9125.33694627, 9163.51905214, 9122.41994862,
       9158.070875  , 9338.36207765, 9246.34048355, 9172.42322629,
       9120.87792644, 9283.76076501, 9268.96900069, 9282.79583804,
       9359.21848381, 9132.40933446, 9307.5344505 , 9333.81556815,
       9225.51734481, 9326.93563419, 9132.73695586, 9128.70693972,
       9118.31799338, 9168.49306186, 9145.52667669, 9305.986746  ,
       9317.30895456, 9169.92885259, 9114.29251795, 9114.22601583,
       9225.48234731, 9147.70180769, 9348.09152942, 9361.83824763,
       9117.14507617, 9143.49779125, 9195.73085494, 9329.34368758,
       9135.08314594, 9184.38439731, 9232.69600836, 9247.17359361,
       9126.83546742, 9214.64981526, 9244.80573343, 9265.90712936,
       9175.66403105, 9215.50968432, 9349.73577441, 9121.13941182,
       9124.77069632, 9256.95838955, 9294.3675932 , 9114.2688922 ,
       9134.29314357, 9271.44159362, 9258.22088261, 9365.99699834,
       9303.25895057, 9370.22537571, 9297.36876875, 9293.39458285,
       9116.23985021, 9158.24037163, 9361.3320643 , 9183.11145418,
       9139.18475391, 9240.44292722, 9327.22173299, 9281.92303829,
       9340.83101045, 9119.26652222, 9137.19134764, 9138.7423889 ,
       9127.09755274, 9139.20020952, 9153.06948195, 9293.8080151 ,
       9116.60735383, 9284.81855485, 9135.21522356, 9226.61058812,
       9114.03336275, 9246.11166062, 9116.78527694, 9333.26930671,
       9353.55935109, 9345.38653741, 9311.24956428, 9117.63388252,
       9332.67227853, 9164.62756344, 9223.56408556, 9297.32411104,
       9122.66863835, 9366.75996546, 9334.73906579, 9366.46549178,
       9366.27853556, 9126.65009319, 9359.03068258, 9272.16877723])

In [50]:
sv.score(x_test, y_test)

-0.1344441061397712

In [51]:
pred[0:20]

array([9284.70136804, 9153.31174498, 9304.75398383, 9167.10855523,
       9170.26299602, 9291.53080107, 9132.26460727, 9124.54795089,
       9248.42951737, 9288.82724377, 9349.35852994, 9308.43755094,
       9172.19186389, 9352.43387792, 9194.13768871, 9260.16986502,
       9119.77267228, 9198.76431594, 9139.31242356, 9153.05227249])

In [56]:
from sklearn.tree import DecisionTreeRegressor

In [57]:
dtr = DecisionTreeRegressor()
dtr.fit(x_train,y_train)
pred = dtr.predict(x_test)
pred

array([ 9361.3268 ,  4877.98105, 10848.1343 , 44585.45587,  4673.3922 ,
       10269.46   , 37484.4493 ,  2154.361  , 19144.57652, 10702.6424 ,
       13616.3586 , 23065.4207 , 51194.55914, 13470.86   ,  5836.5204 ,
        8516.829  ,  2362.22905, 39774.2763 , 23241.47453,  4040.55825,
        1748.774  , 20296.86345, 10370.91255, 20296.86345, 37079.372  ,
        7418.522  , 42560.4304 , 46130.5265 ,  9910.35985,  9563.029  ,
        3761.292  ,  9386.1613 ,  1837.237  , 12913.9924 , 48549.17835,
        9283.562  ,  4915.05985,  4906.40965, 22412.6485 ,  8823.279  ,
        1633.9618 , 18767.7377 , 41034.2214 ,  9290.1395 ,  9500.57305,
        3732.6251 ,  1634.5734 ,  7727.2532 ,  4337.7352 ,  6986.697  ,
        4922.9159 ,  5438.7491 , 21880.82   ,  1880.487  ,  7160.3303 ,
        8116.26885,  9617.66245,  3208.787  , 51194.55914,  6600.361  ,
       11299.343  ,  5246.047  , 29186.48236,  1708.0014 , 12485.8009 ,
       12094.478  ,  6112.35295, 21774.32215, 17178.6824 , 14418.2804 ,
       10197.7722 , 21344.8467 ,  5125.2157 ,  2585.269  , 10214.636  ,
        1727.785  , 12982.8747 ,  5124.1887 ,  9855.1314 , 13217.0945 ,
        3956.07145, 12485.8009 , 12648.7034 ,  7740.337  , 28868.6639 ,
       12928.7911 ,  2866.091  ,  1720.3537 ,  1759.338  ,  1826.843  ,
       14590.63205, 17663.1442 ,  6799.458  , 16586.49771,  1744.465  ,
       42856.838  , 27346.04207,  8026.6666 ,  1136.3994 ,  8603.8234 ,
       14043.4767 , 11987.1682 , 22218.1149 , 26467.09737, 40182.246  ,
        1628.4709 , 43943.8761 , 21472.4788 , 12495.29085,  4747.0529 ,
        6311.952  , 12224.35085, 14358.36437,  6196.448  ,  2026.9741 ,
        1981.5819 ,  2709.24395,  2207.69745,  1826.843  , 10156.7832 ,
       44641.1974 ,  3704.3545 ,  7147.4728 ,  6196.448  ,  7421.19455,
        6986.697  ,  4915.05985, 13429.0354 , 39611.7577 , 48173.361  ,
       28868.6639 , 12797.20962,  3070.8087 , 10702.6424 ,  6196.448  ,
       17128.42608, 48885.13561, 18767.7377 , 17352.6803 ,  2850.68375,
       18157.876  ,  3981.9768 , 40419.0191 , 10422.91665,  1634.5734 ,
        5910.944  ,  4536.259  ,  7742.1098 , 41676.0811 , 13974.45555,
        6082.405  ,  6652.5288 ,  4747.0529 , 14901.5167 ,  6710.1919 ,
       36397.576  , 42560.4304 ,  8527.532  ,  7789.635  ,  8457.818  ,
       10338.9316 ,  4500.33925, 11840.77505, 11848.141  , 45008.9555 ,
       39725.51805, 10848.1343 , 17560.37975,  2632.992  ,  4005.4225 ,
        4441.21315, 12890.05765,  3554.203  , 22192.43711,  7727.2532 ,
       16776.30405, 12609.88702, 26392.26029,  8627.5411 ,  8968.33   ,
       13224.693  ,  2850.68375, 11244.3769 , 22192.43711, 38415.474  ,
       10214.636  ,  3393.35635, 26018.95052,  1731.677  , 44585.45587,
        2632.992  , 21978.6769 , 10338.9316 ,  4350.5144 ,  1615.7667 ,
       21344.8467 , 38415.474  ,  4340.4409 , 14001.1338 , 14235.072  ,
       33732.6867 , 17496.306  ,  5272.1758 , 10601.63225, 18648.4217 ,
       14358.36437,  7954.517  ,  8116.26885, 13126.67745, 43753.33705,
       23401.30575,  9500.57305,  4350.5144 ,  8252.2843 , 13012.20865,
        1631.8212 ,  2166.732  ,  7147.4728 ,  8444.474  ,  2128.43105,
        2632.992  , 45702.02235, 48885.13561, 16455.70785,  9288.0267 ,
       47928.03   , 41919.097  ,  9264.797  , 34472.841  ,  5125.2157 ,
       12982.8747 , 37079.372  ,  4846.92015,  5699.8375 , 10577.087  ,
       21232.18226, 13012.20865,  2211.13075,  2632.992  ,  3392.3652 ,
        4466.6214 ,  2897.3235 ,  4040.55825, 10106.13425,  1632.56445,
       10156.7832 ,  4827.90495,  6196.448  ,  2200.83085,  8116.26885,
       18218.16139, 11455.28   , 12730.9996 , 13430.265  , 44260.7499 ,
       12829.4551 , 22192.43711,  5253.524  ,  7640.3092 ,  9630.397  ,
       35585.576  , 47928.03   , 11987.1682 , 14901.5167 , 13981.85035,
        3987.926  , 48517.56315,  8442.667  ])

In [58]:
dtr.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [59]:
df.to_csv('insurance.csv',index=False)